services:
  app:
    image: manologcode/long_text_coqui
    build: .
    restart: always
    container_name: long_text_coqui
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5008"]
    ports:
      - "5008:5008"
    volumes:
      - ./app:/app
    environment:
      - SERVER_URL_COQUI_XTTS=http://192.168.1.69:8820

